---
title: "Child Mortality (visualization using shiny and ggplot2)"
author: "Muhsina Elampilakkattil"
date: "11 December 2018"
runtime: shiny
output: 
  html_document:
    toc: true
    code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}

library(shiny)
library(colourpicker)
library(tidyverse)
library(gapminder)


#Load child mortality data
mortality<- read_csv("datasets/child_mortality.csv");

#Load GDP Per Capita data
income<- read_csv("datasets/income.csv")

#Load mean year in school data
education<- read_csv("datasets/education.csv")

#Load dataset for anemia in pregnent women
anemia<- read_csv("datasets/prg_anem.csv")

# Use gather to move the year dimension as a column
education <- gather(education, year, mean_year, -country)
mortality <- gather(mortality, year, child_mortality, -country)
income <- gather(income, year, gdp, -country)
anemia<- gather(anemia, year, prg_anem, -country)

population <- gapminder %>%
  select(country, year, pop) 


df <- merge(education, mortality, by=c("country","year"), header =T)
df <- df%>% 
  filter(!is.na(child_mortality))

df <- merge(df, income, by=c("country","year"), header =T)
df <- merge(df, anemia, by=c("country", "year"), header= T)

#df <- merge(df, population, by=c("country", "year"), header= T)
continent<- gapminder%>%
  group_by(continent, country)%>%
  distinct(country, continent)

continent<- data.frame(lapply(continent, as.character), stringsAsFactors= FALSE)

# Filter out all countries that do not exist in the continent table
df <- df %>% filter(country %in% unique(continent$country))

# Add the continent column to finalize the data set
df <- merge(df, continent, by=c("country"), header =T)

df$year <- as.numeric(df$year)

# Define UI for application that plots features of movies
ui <- fluidPage(
  
  # Sidebar layout with a input and output definitions
  sidebarLayout(
    
    # Inputs
    sidebarPanel(

      
      # Select variable for y-axis
      selectInput(inputId = "y", 
                  label = "Y-axis:",
                  choices = c("Child Mortality" = "child_mortality", 
                              "Average Year in School(Female)" = "mean_year", 
                              "GDP Per Capita" = "gdp", 
                              "Anemic Pregnant Women" = "prg_anem"),
                  selected = "mean_year"),
      
      # Select variable for x-axis
      selectInput(inputId = "x", 
                  label = "X-axis:",
                  choices = c("Child Mortality" = "child_mortality", 
                              "Average Year in School(Female)" = "mean_year", 
                              "GDP Per Capita" = "gdp", 
                              "Anemic Pregnant Women" = "prg_anem"), 
                  selected = "child_mortality"),
      
      # Select variable for year
      sliderInput(inputId = "year", 
                  label = "Year:",
                  min= 1990,
                  max= 2016,
                  value= 1990),
      
      # Set alpha level
      sliderInput(inputId = "alpha", 
                  label = "Alpha:", 
                  min = 0, max = 1, 
                  value = 0.5),
      checkboxGroupInput(inputId = "continent", 
                         label = "Continents:",
                          choices = c( 'Asia',
                        'Europe', 
                        'Africa', 
                        'Americas',
                        'Oceania'),
                        selected = c( 'Asia',
                        'Europe', 
                        'Africa', 
                        'Americas',
                        'Oceania'))
                     
    ),
    
    # Outputs
    mainPanel(
      plotOutput(outputId = "scatterplot")
    )
  )
)

# Define server function required to create the scatterplot
server <- function(input, output) {
  
  # Create scatterplot object the plotOutput function is expecting
  output$scatterplot <- renderPlot({
    df%>%
  filter(year== input$year,
        continent %in% input$continent)%>%
         group_by(continent) %>%
    ggplot( aes_string(x = input$x, y = input$y)) +
      geom_point(alpha = input$alpha)
  })
}

# Create the Shiny app object
shinyApp(ui = ui, server = server)


```